include_dirs = Split('. /usr/local/include/proto')

libs = Split('')

lib_dirs = Split('')
installed_plugins_dir = Split('../../plugin_lib')

# shared library for SimpleLifeCycle plugin
simple_life_cycle_layer_source_files = Split('SimpleLifeCycle.cpp SimpleLifeCyclePlugin.cpp')
slc_dll = SharedLibrary('simple-life-cycle', source = simple_life_cycle_layer_source_files, CPPPATH = include_dirs, LIBS = libs, LIBPATH = lib_dirs)
Install(dir = installed_plugins_dir, source = slc_dll)
#StaticLibrary('simple-life-cycle', source = simple_life_cycle_layer_source_files, CPPPATH = include_dirs, LIBS = libs, LIBPATH = lib_dirs)
