# shared library for Mica2Motes plugin
mica2mote_layer_source_files = Split('Mica2Mote.cpp Mica2MotePlugin.cpp')
m2m_dll = SharedLibrary('mica2mote', source = mica2mote_layer_source_files, CPPPATH = include_dirs, LIBS = libs, LIBPATH = lib_dirs)
Install(dir = installed_plugins_dir, source = m2m_dll)
