include_dirs = Split('. /usr/local/include/proto')

libs = Split('')

lib_dirs = Split('')
installed_plugins_dir = Split('../../plugin_lib')

# shared library for radio plugin
radio_models_layer_source_files = Split('RadioModelsPlugin.cpp wormhole-radio.cpp multiradio.cpp')
rm_dll = SharedLibrary('radiomodels', source = radio_models_layer_source_files, CPPPATH = include_dirs, LIBS = libs, LIBPATH = lib_dirs)
Install(dir = installed_plugins_dir, source = rm_dll)
