#! /bin/sh
# shell script to run p2b with necessary arguments to run from source dir

mydir=`dirname "${0}"`

if ! test -x "${mydir}/src/p2b"; then
    echo "Cannot find src/p2b"
    exit 1
fi

exec "${mydir}/src/p2b" -path . --srcdir "${mydir}" "${@}"
