#! /bin/sh
# shell script to run proto with necessary arguments to run from source dir

mydir=`dirname "${0}"`

if ! test -x "${mydir}/src/proto"; then
    echo "Cannot find src/proto"
    exit 1
fi

export LD_LIBRARY_PATH="${mydir}/src/sim/plugins/:/usr/local/lib/:$LD_LIBRARY_PATH"

exec "${mydir}/src/proto" --srcdir "${mydir}" "${@}"
