include_dirs = Split('. ../ ../shared ../kernel')
libs = Split('sim kernel compiler shared dl')
lib_dirs = Split('./.libs ../shared/.libs ../kernel/.libs ../compiler/.libs')

# shared library for distributions
distributions_source_files = Split('XGrid.cpp FixedPoint.cpp Grid.cpp GridRandom.cpp Cylinder.cpp Torus.cpp DistributionsPlugin.cpp')
SharedLibrary('distributions', source = distributions_source_files, CPPPATH = include_dirs, LIBS = libs, LIBPATH = lib_dirs)

# shared library for SimpleLifeCycle plugin
simple_life_cycle_layer_source_files = Split('SimpleLifeCycle.cpp')
SharedLibrary('simple-life-cycle', source = simple_life_cycle_layer_source_files, CPPPATH = include_dirs, LIBS = libs, LIBPATH = lib_dirs)
#StaticLibrary('simple-life-cycle', source = simple_life_cycle_layer_source_files, CPPPATH = include_dirs, LIBS = libs, LIBPATH = lib_dirs)

# shared library for Mica2Motes plugin
mica2mote_layer_source_files = Split('Mica2Mote.cpp')
SharedLibrary('mica2mote', source = mica2mote_layer_source_files, CPPPATH = include_dirs, LIBS = libs, LIBPATH = lib_dirs)

# shared library for radio plugin
radio_models_layer_source_files = Split('RadioModelsPlugin.cpp wormhole-radio.cpp multiradio.cpp')
SharedLibrary('radiomodels', source = radio_models_layer_source_files, CPPPATH = include_dirs, LIBS = libs, LIBPATH = lib_dirs)

registry_source_files = Split('createRegistry.cpp')
registry_libs = Split('dl')
Program(source = registry_source_files, LIBS = registry_libs)