include_dirs = Split('. ../shared')

#libs = Split('xerces-c cv')

source_files = Split('XGrid.cpp FixedPoint.cpp Grid.cpp GridRandom.cpp Cylinder.cpp Torus.cpp')
#StaticLibrary(source = source_files, CPPPATH = include_dirs)
SharedLibrary('distributions', source = source_files, CPPPATH = include_dirs)