#!/usr/bin/python

import cgi, cgitb
import subprocess

form = cgi.FieldStorage()

program = form.getvalue('program')

print("Content-type: application/json\n\n")

output = subprocess.Popen(['/home/kusbeck/proto/svn_trunk/proto/src/p2b', '--instructions', program], stdout=subprocess.PIPE).communicate()[0]

print(output)

